# -*- coding: utf-8 -*-
"""Merge_CSVNew.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g0JFqRinvhewa5QrPAmLbgvLIrA-1KZM
"""

import csv
import os
import pandas as pd

mypath='/content/drive/MyDrive/Merge_CSV'
os.chdir(mypath)

def new_data_file(fname):
  data = pd.read_csv(f'{fname}')
  with open('new_master.csv', 'w') as csv_write:
    new_data=csv.writer(csv_write)
    for x in range(len(data.index)):
      lst=[]
      for y in range(4):
        head, tail = os.path.split(data.iloc[x,y])
        lst.append("home/infrrd/new_data/" + tail)
      lst.append(data.iloc[x,4])
      new_data.writerow(lst)

def pass_file(file_list):
  for files in file_list:
    new_data_file(files)

files = [f for f in os.listdir(mypath) if os.path.isfile(os.path.join(mypath, f))]
pass_file(files)

